pr: none
trigger:
  batch: true
  branches:
    include:
      - "*"
  tags:
    include:
      - "dev-*"

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: Build
    dependsOn: []
    jobs:
      - job: build
        displayName: Build Docker Images
        steps:
          - script: docker build --target=base --tag keboola/job-runner .
            displayName: Build Docker images
          - template: azure-pipelines/steps/store-docker-artifact.yml

  # push to production (dev-* tags)
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/dev-') }}:
      - stage: publishImages_production
        displayName: Publish Images to GitOps Lab GAR
        dependsOn: [build]
        jobs:
          - job:
            displayName: Publish Docker Images
            steps:
              - template: azure-pipelines/steps/restore-docker-artifact.yml
              - template: azure-pipelines/steps/push-docker-image.yml
                parameters:
                  displayName: GitOps Lab GAR
                  garPushEnabled: True
                  garRegistry: "Keboola GAR GitOps Lab"
                  garRepository: europe-west3-docker.pkg.dev/gitops-stacks-provisioning
                  garRepositoryProjectId: gitops-stacks-provisioning
                  sourceImage: keboola/job-runner
                  targetImage: job-runner
                  tags:
                    - ${{ replace(variables['Build.SourceBranch'],'refs/tags/','') }}
