pr: none
trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
  imageName: 'job-runner'
  tag: $(Build.BuildId)
  productionTag: production-$(Build.SourceVersion)

stages:
  - stage: prepare
    displayName: Prepare & Test 
    pool:
      name: 'Default'
    jobs:
      - job: test
        displayName: 'Test'
        steps:
          - task: Docker@2
            displayName: Test ACR login
            inputs:
              command: login
              containerRegistry: 'Keboola PS Test ACR'

          - script: |
              docker-compose down
              docker-compose build
              docker-compose pull internal-api
            displayName: 'Build Tests'

          - script: docker-compose run tests
            displayName: 'Run Tests'
            env:
              CPU_COUNT: $(CPU_COUNT)
              LEGACY_OAUTH_API_URL: $(LEGACY_OAUTH_API_URL)
              LEGACY_ENCRYPTION_KEY: $(LEGACY_ENCRYPTION_KEY)
              JOB_QUEUE_URL: $(JOB_QUEUE_URL)
              JOB_QUEUE_TOKEN: $(JOB_QUEUE_TOKEN)
              STORAGE_API_URL: $(STORAGE_API_URL)
              AWS_REGION: $(AWS_REGION)
              AWS_KMS_KEY_ID: $(AWS_KMS_KEY_ID)
              AWS_LOGS_S3_BUCKET: $(AWS_LOGS_S3_BUCKET)
              AZURE_KEY_VAULT_URL: $(AZURE_KEY_VAULT_URL)
              AZURE_LOG_ABS_CONNECTION_STRING: $(AZURE_LOG_ABS_CONNECTION_STRING)
              AZURE_LOG_ABS_CONTAINER: $(AZURE_LOG_ABS_CONTAINER)
              TEST_STORAGE_API_TOKEN: $(TEST_STORAGE_API_TOKEN)
              TEST_AWS_ACCESS_KEY_ID: $(TEST_AWS_ACCESS_KEY_ID)
              TEST_AWS_SECRET_ACCESS_KEY: $(TEST_AWS_SECRET_ACCESS_KEY)
              TEST_AZURE_CLIENT_ID: $(TEST_AZURE_CLIENT_ID)
              TEST_AZURE_CLIENT_SECRET: $(TEST_AZURE_CLIENT_SECRET)
              TEST_AZURE_TENANT_ID: $(TEST_AZURE_TENANT_ID)

  # Push test image to test ACR
  - stage: deploy_test
    displayName: Deploy Test
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: deploy
        displayName: 'Deploy'
        steps:
          - task: Docker@2
            displayName: Build and tag the image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              repository: keboolapes.azurecr.io/$(imageName)
              tags: |
                $(tag)
                $(productionTag)
                latest

          - task: Docker@2
            displayName: Push the image to Test ACR
            inputs:
              containerRegistry: 'Keboola PS Test ACR'
              repository: $(imageName)
              command: push
              tags: |
                $(tag)
                $(productionTag)

          - task: Docker@2
            displayName: Push latest image to Test ACR
            inputs:
              containerRegistry: 'Keboola PS Test ACR'
              repository: $(imageName)
              command: push
              tags: |
                latest
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  # Push image to production ACR
  - stage: deploy_prod
    displayName: Deploy Production
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: deploy
        displayName: 'Deploy'
        steps:
          - task: Docker@2
            displayName: Build and tag the image
            inputs:
              command: buildAndPush
              containerRegistry: 'Keboola ACR'
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              repository: keboola.azurecr.io/$(imageName)
              tags: |
                $(productionTag)
                latest

          - script: |
              printf "%s" "$(productionTag)" > artifact
            displayName: Create artifact

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'artifact'
              artifact: 'keboola.job-runner.latest-build'
