#pool:
#  vmImage: 'ubuntu-latest'
pool:
  name: 'Default'

steps:
- script: docker info
  displayName: 'Info'

- script: docker-compose build
  displayName: 'Build Tests'

- script: docker-compose run tests
  displayName: 'Run Tests'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    STORAGE_API_URL: $(KBC_TEST_URL)
    KBC_TEST_TOKEN: $(KBC_TEST_TOKEN)
    KEBOOLA_STACK: $(KEBOOLA_STACK)
    REGION: $(REGION)
    CPU_COUNT: $(CPU_COUNT)
    KMS_KEY: $(KMS_KEY)
    LEGACY_OAUTH_API_URL: $(LEGACY_OAUTH_API_URL)
    LOGS_S3_BUCKET: $(LOGS_S3_BUCKET)
    JOB_QUEUE_URL: $(JOB_QUEUE_URL)
    JOB_QUEUE_TOKEN: $(JOB_QUEUE_TOKEN)

- script: |
    docker build -t keboola/job-runner .
    eval $(docker run --rm -i -e AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) -e AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY) quay.io/keboola/aws-cli ecr get-login --region us-east-1 --no-include-email)
    docker tag keboola/job-runner:latest $(ECR_REPOSITORY_URI):$(Build.SourceVersion)
    docker tag keboola/job-runner:latest $(ECR_REPOSITORY_URI):latest
    docker push $(ECR_REPOSITORY_URI):$(Build.SourceVersion)
    docker push $(ECR_REPOSITORY_URI):latest
  displayName: 'Push to Dev AWS'

- script: |
    docker build -t keboola/job-runner .
    eval $(docker run --rm -i -e AWS_ACCESS_KEY_ID=$(PROD_AWS_ACCESS_KEY_ID) -e AWS_SECRET_ACCESS_KEY=$(PROD_AWS_SECRET_ACCESS_KEY) quay.io/keboola/aws-cli ecr get-login --region us-east-2 --no-include-email)
    docker tag keboola/job-runner:latest $(US_EAST_2_ECR_REPOSITORY_URI):$(Build.SourceVersion)
    docker tag keboola/job-runner:latest $(US_EAST_2_ECR_REPOSITORY_URI):latest
    docker push $(US_EAST_2_ECR_REPOSITORY_URI):$(Build.SourceVersion)
    docker push $(US_EAST_2_ECR_REPOSITORY_URI):latest
  displayName: 'Push to US-EAST-2'

