pr: none
trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
  imageName: 'job-runner'
  tag: $(Build.BuildId)
  productionTag: production-$(Build.SourceVersion)

stages:
  - stage: Prepare
    pool:
      name: 'Default'
    jobs:
      - job: test
        displayName: 'Test'
        steps:
          - task: Docker@2
            displayName: Test ACR login
            inputs:
              command: login
              containerRegistry: 'Keboola PS Test ACR'

          - script: docker-compose build
            displayName: 'Build Tests'

          - script: docker-compose run tests
            displayName: 'Run Tests'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              STORAGE_API_URL: $(KBC_TEST_URL)
              KBC_TEST_TOKEN: $(KBC_TEST_TOKEN)
              KEBOOLA_STACK: $(KEBOOLA_STACK)
              REGION: $(REGION)
              CPU_COUNT: $(CPU_COUNT)
              KMS_KEY: $(KMS_KEY)
              LEGACY_OAUTH_API_URL: $(LEGACY_OAUTH_API_URL)
              LOGS_S3_BUCKET: $(LOGS_S3_BUCKET)
              JOB_QUEUE_URL: $(JOB_QUEUE_URL)
              JOB_QUEUE_TOKEN: $(JOB_QUEUE_TOKEN)

  - stage: Deploy
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: deploy
        displayName: 'Deploy'
        steps:
          - task: Docker@2
            displayName: Build and tag the image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              repository: $(imageName)
              tags: |
                $(tag)
                $(productionTag)
                latest

          # Push test image to test ACR
          - task: Docker@2
            displayName: Test ACR login
            inputs:
              command: login
              containerRegistry: 'Keboola PS Test ACR'

          - script: |
              docker tag $(imageName):$(tag) keboolapes.azurecr.io/$(imageName):$(tag)
              docker tag $(imageName):latest keboolapes.azurecr.io/$(imageName):latest
              docker images
            displayName: Tag the image for Test ACR

          - task: Docker@2
            displayName: Push the test image to Test ACR
            inputs:
              containerRegistry: 'Keboola PS Test ACR'
              repository: $(imageName)
              command: push
              tags: |
                $(tag)
                latest
