pr: none
trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - 'dev-*'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: Build
    dependsOn: []
    jobs:
      - job: build
        displayName: Build Docker Images
        steps:
          - script: docker build --target=base --tag keboola/job-runner .
            displayName: Build Docker images

          - template: azure-pipelines/steps/store-docker-artifact.yml

  # push to production (dev-* tags)
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/dev-') }}:
      - stage: publishImages_production
        displayName: Publish Production Images (dev tag)
        dependsOn: [build]
        jobs:
          - job:
            displayName: Publish Docker Images
            steps:
              - template: azure-pipelines/steps/restore-docker-artifact.yml
              - template: azure-pipelines/steps/push-docker-image.yml
                parameters:
                  displayName: Production
                  awsCredentials: Production - ECR Distribution
                  awsRegionName: us-east-1
                  acrRegistry: keboola.azurecr.io
                  garPushEnabled: True
                  garRegistry: Keboola GAR
                  garRepository: us-central1-docker.pkg.dev/keboola-prod-artifacts
                  garRepositoryProjectId: keboola-prod-artifacts
                  sourceImage: keboola/job-runner
                  targetImage: job-runner
                  tags:
                    - ${{ replace(variables['Build.SourceBranch'],'refs/tags/','') }}
