pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker info
  displayName: 'Info'

- script: docker-compose build
  displayName: 'Build Tests'

- script: docker-compose run tests
  displayName: 'Run Tests'

- script: |
    docker build -t keboola/job-runner .
    yes | eval $(docker run --rm -i -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY quay.io/keboola/aws-cli ecr get-login --region us-east-1 --no-include-email)
    docker tag keboola/job-runner:latest $ECR_REPOSITORY_URI:$COMMIT_ID
    docker tag keboola/job-runner:latest $ECR_REPOSITORY_URI:latest
    docker push $ECR_REPOSITORY_URI:$COMMIT_ID
    docker push $ECR_REPOSITORY_URI:latest 
  displayName: 'Push to Dev AWS'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    KBC_TEST_URL: $(KBC_TEST_URL)
    KBC_TEST_TOKEN: $(KBC_TEST_TOKEN)
    ECR_REPOSITORY_URI: $(ECR_REPOSITORY_URI)
    COMMIT_ID: $(Build.SourceVersion)
