#pool:
#  vmImage: 'ubuntu-latest'
pool:
  name: 'Default'

steps:
- script: docker info
  displayName: 'Info'

- script: docker-compose build
  displayName: 'Build Tests'

- script: docker-compose run tests
  displayName: 'Run Tests'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    STORAGE_API_URL: $(KBC_TEST_URL)
    KBC_TEST_TOKEN: $(KBC_TEST_TOKEN)
    KEBOOLA_STACK=job-runner-test
    REGION=us-east-1
    CPU_COUNT=1
    KMS_KEY=cca3d50b-353c-4a5d-aa94-10a24f8bc6b0
    LEGACY_OAUTH_API_URL=https://syrup.keboola.com/oauth-v2/
    LOGS_S3_BUCKET=connection-testing-services-s3logsbucket-nz8zaaeo5ve6
    JOB_QUEUE_URL=https://9v6f8zdu63.execute-api.eu-central-1.amazonaws.com/test/jobs
    JOB_QUEUE_TOKEN=dummy


- script: |
    docker build -t keboola/job-runner .
    yes | eval $(docker run --rm -i -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY quay.io/keboola/aws-cli ecr get-login --region us-east-1 --no-include-email)
    docker tag keboola/job-runner:latest $ECR_REPOSITORY_URI:$COMMIT_ID
    docker tag keboola/job-runner:latest $ECR_REPOSITORY_URI:latest
    docker push $ECR_REPOSITORY_URI:$COMMIT_ID
    docker push $ECR_REPOSITORY_URI:latest 
  displayName: 'Push to Dev AWS'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    ECR_REPOSITORY_URI: $(ECR_REPOSITORY_URI)
    COMMIT_ID: $(Build.SourceVersion)
