FROM keboola/job-runner

ENV APP_ENV dev

RUN pecl channel-update pecl.php.net \
    && pecl config-set php_ini /usr/local/etc/php.ini \
    && pecl install xdebug-beta \
    && docker-php-ext-enable xdebug

CMD [/bin/bash]
