version: '3'
# for development purposes only

services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
    image: keboola/job-runner

  tests: &tests
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: 
      composer ci

  tests-local: 
    <<: *tests
    volumes:
      - ./:/code
      - /tmp/:/tmp/
      - /var/run/docker.sock:/var/run/docker.sock      
    environment:
      - JOB_ID
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    command:
      - php 
      - /code/bin/console 
      - app:run
