version: '3.4'
# for development purposes only

services:
  production:
    build:
      context: .
      target: base
    image: keboola/job-runner

  tests: &tests
    build:
      context: .
      target: dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/:/tmp/
    environment:
      - CPU_COUNT
      - JOB_QUEUE_URL
      - JOB_QUEUE_TOKEN
      - STORAGE_API_URL
      - VAULT_API_URL
      - AWS_REGION
      - AWS_KMS_KEY_ID
      - AWS_LOGS_S3_BUCKET
      - AZURE_KEY_VAULT_URL
      - AZURE_LOG_ABS_CONNECTION_STRING
      - AZURE_LOG_ABS_CONTAINER
      - ENCRYPTOR_STACK_ID
      - TEST_STORAGE_API_TOKEN
      - TEST_STORAGE_API_TOKEN_MASTER
      - TEST_AWS_ACCESS_KEY_ID
      - TEST_AWS_SECRET_ACCESS_KEY
      - TEST_AZURE_CLIENT_ID
      - TEST_AZURE_CLIENT_SECRET
      - TEST_AZURE_TENANT_ID

    command:
      composer ci
    depends_on:
      - internal-api

  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./:/code
      - /tmp/:/tmp/
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - /bin/bash

  internal-api:
    image: keboolapes.azurecr.io/job-queue-internal-api:latest
    ports:
      - "81:8080"
    volumes:
      # to get wait-for-it
      - ./:/build-code
    environment:
      - log_abs_connection_string=
      - log_abs_container=debug-files
      - logs_s3_bucket=
      - logs_s3_bucket_region=
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=jobs
      - DATABASE_SSL_VERIFY_ENABLED=0
      - JOB_QUEUE_INTERNAL_API_AUTH_TOKEN=${JOB_QUEUE_TOKEN}
      - STORAGE_API_URL=${STORAGE_API_URL}
      - MANAGE_API_TOKEN=${TEST_INTERNAL_API_APPLICATION_TOKEN}
      - APP_ENV=dev

    command: ['sh', '-c', '/build-code/docker/wait-for-it.sh --strict --timeout=120 mysql:3306 -- composer migrate-db && apache2-foreground']
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=jobs
      - MYSQL_ROOT_PASSWORD=root
