version: '3.4'
# for development purposes only

services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./:/code
      - /tmp/:/tmp/
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - /bin/bash
    depends_on:
      - internal-api

  ci:
    build:
      context: .
      target: base
    image: keboola/job-runner
    command: composer ci
    env_file:
      - .env
      - .env.test
    environment:
      APP_ENV: test
      TEST_STORAGE_API_TOKEN:
      TEST_STORAGE_API_TOKEN_MASTER:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/:/tmp/
      - ./var/gcp-private-key.json:/code/var/gcp-private-key.json
    depends_on:
      - internal-api

  internal-api:
    image: keboolapes.azurecr.io/job-queue-internal-api:latest
    ports:
      - "81:8080"
    volumes:
      # to get wait-for-it
      - ./:/build-code
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=jobs
      - DATABASE_SSL_VERIFY_ENABLED=0
      - JOB_QUEUE_INTERNAL_API_AUTH_TOKEN=dummy-token
      - STORAGE_API_URL=${STORAGE_API_URL}
      - MANAGE_API_TOKEN=${TEST_INTERNAL_API_APPLICATION_TOKEN}
      - APP_ENV=dev
      - HOSTNAME_SUFFIX=keboola.com

    command: ['sh', '-c', '/build-code/docker/wait-for-it.sh --strict --timeout=120 mysql:3306 -- composer migrate-db && apache2-foreground']
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=jobs
      - MYSQL_ROOT_PASSWORD=root
