version: '3'
# for development purposes only

services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
    image: keboola/job-runner

  tests: &tests
    build:
      context: .
      dockerfile: Dockerfile-tests
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/:/tmp/
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - CPU_COUNT
      - JOB_QUEUE_URL
      - JOB_QUEUE_TOKEN
      - KBC_TEST_TOKEN
      - KMS_KEY
      - LEGACY_OAUTH_API_URL
      - LOGS_S3_BUCKET
      - REGION
      - STORAGE_API_URL
    command: 
      composer ci

  tests-local: 
    <<: *tests
    volumes:
      - ./:/code
      - /tmp/:/tmp/
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - /bin/bash
