FROM keboola/job-runner

ENV APP_ENV dev

# install extensions
RUN pecl channel-update pecl.php.net \
	&& pecl config-set php_ini /usr/local/etc/php.ini \
    && yes | pecl install xdebug-2.9.8 \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.idekey=PHPSTORM" >> /usr/local/etc/php/conf.d/xdebug.ini

CMD [/bin/bash]
