monolog:
    handlers:
        main:
            type: stream
            path: php://stderr
            formatter: Monolog\Formatter\JsonFormatter
            level: info
            channels: ["!event", "!request"]
