monolog:
    handlers:
        main:
            type: stream
            path: php://stdout
            formatter: Monolog\Formatter\JsonFormatter
            level: notice
            channels: ["!event", "!request", "!php"]
