---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev-job-queue-internal-api
  labels:
    app: dev-job-queue-internal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-job-queue-internal-api
  template:
    metadata:
      labels:
        app: dev-job-queue-internal-api
      annotations:
        log: "true"
    spec:
      containers:
        - name: dev-mysql
          image: mysql:8
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          ports:
            - containerPort: 3306
          args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: 'jobs'
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'
        - name: dev-job-queue-internal-api
          image: keboolapes.azurecr.io/job-queue-internal-api:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 80
          command:
            - "/bin/sh"
          args: 
            - "-c"
            - 'printf "waiting" && sleep 20 && printf "migrating" && php bin/console doctrine:schema:update --force && apache2-foreground'
          env:
            - name: storage_api_url
              value: 'https://connection.keboola.com'
            - name: logs_s3_bucket
              value: ''
            - name: log_abs_container
              value: ''
            - name: log_abs_connection_string
              value: ''
            - name: DATABASE_HOST
              value: '127.0.0.1'
            - name: DATABASE_PORT
              value: '3306'
            - name: DATABASE_USER
              value: 'root'
            - name: DATABASE_PASSWORD
              value: 'root'
            - name: DATABASE_NAME
              value: 'jobs'
          readinessProbe:
            httpGet:
              path: /health-check
              port: 80
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 80
              path: /health-check
              httpHeaders:
                - name: Host
                  value: KubernetesLivelinessProbe
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: dev-job-queue-internal-api
  name: dev-job-queue-internal-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: dev-job-queue-internal-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
