parameters:
  - name: displayName
    type: string

  - name: condition
    type: string
    default: True

  - name: garPushEnabled
    type: string
    default: False

  - name: garRegistry
    type: string
    default: ""

  - name: garRepository
    type: string
    default: ""

  - name: garRepositoryProjectId
    type: string
    default: ""

  - name: sourceImage
    type: string

  - name: targetImage
    type: string

  - name: tags
    type: object

steps:
  - template: push-gar.yml
    parameters:
      displayName: Push GAR - ${{ parameters.displayName }}
      condition: ${{ parameters.condition }}
      garPushEnabled: ${{ parameters.garPushEnabled }}
      garRegistry: ${{ parameters.garRegistry }}
      garRepository: ${{ parameters.garRepository }}
      garRepositoryProjectId: ${{ parameters.garRepositoryProjectId }}
      sourceImage: ${{ parameters.sourceImage }}
      targetImage: ${{ parameters.targetImage }}
      tags: ${{ parameters.tags }}
