parameters:
  - name: name
    type: string
    default: docker-images

  - name: dockerArtifactFile
    type: string
    default: docker-images.tar


steps:
  - download: current
    artifact: ${{ parameters.name }}
    displayName: Download artifacts

  - script: docker load --input $(Pipeline.Workspace)/${{ parameters.name }}/${{ parameters.dockerArtifactFile }}
    displayName: Load images
